### ISSUE TITLE
'ddp-client' module is missing after 'npm install'

### ISSUE THREAD

**Issue by shaharhalutz** [spencercarli/react-native-redux-meteor#2]
resolved by changing the module's name from 'ddp-client' to 'node-ddp-client',
made changes in:  'RNApp/package.json' and  'RNApp/app/ddp.js'

**Comment by spencercarli** [comment]
Hey! I appreciate you bringing this up. However I'm going to close this as I'm not supporting this repo (it was just an experiment). I'll be releasing a new one, based on my [React Native Meteor Boilerplate](https://github.com/spencercarli/react-native-meteor-boilerplate), next week. Thanks!

**Comment by shaharhalutz** [comment]
no prob 🙂
sounds excellent !
am looking forward to have a peek ...
